#!/bin/bash

APP_DIR="/home/kiteapp"
GIT_DIR="/home/kiteapp.git"
BRANCH="refs/heads/master"

while read oldrev newrev ref
do
    if [ "$ref" = "$BRANCH" ]; then
        echo "Deploying (volume-based)..."

        mkdir -p "$APP_DIR"
        git --work-tree="$APP_DIR" --git-dir="$GIT_DIR" checkout -f master

        cd "$APP_DIR" || exit
        docker compose down
        docker compose up -d  # no build

        echo "Deployment complete (no rebuild)."
    fi
done

# Ensure the script is executable



# chmod +x /home/kiteapp.git/hooks/post-receive
