#!/bin/bash

APP_DIR="/home/kiteapp"
GIT_DIR="/home/kiteapp.git"
BRANCH="refs/heads/master"

while read oldrev newrev ref
do
    if [ "$ref" = "$BRANCH" ]; then
        echo "Deploying Docker stack..."

        # Ensure working dir exists
        mkdir -p "$APP_DIR"

        # Clean copy: no .git folder
        git --work-tree="$APP_DIR" --git-dir="$GIT_DIR" checkout -f master

        cd "$APP_DIR" || exit

        echo "Rebuilding and starting containers..."
        docker compose -f docker-compose.yml down
        docker compose -f docker-compose.yml up -d --build

        echo "Deployment complete."
    fi
done
# Ensure the script is executable



# chmod +x /home/kiteapp.git/hooks/post-receive
